# DATA
data_root: dataset/acdc_2d
classes: 4
modality: mri


# MODEL
arch: unet
in_chan: 1
base_chan: 32
block: SingleConv


# TRAIN
epochs: 1
training_size: [256, 256]    # training crop size
start_epoch: 0
num_workers: 4

split_seed: 0     # random seed for suffle before setting cross validation fold
k_fold: 5   # number of folds in cross validation

optimizer: adamw
base_lr: 0.0005
betas: [0.9, 0.999]
weight_decay: 0.05  
weight: [0.5, 1, 1, 1]  # weitght of each class in the loss function
rlt: 1 # relation between CE and Dice loss

scale: 0.3  # scale for data augmentation
rotate: 180 # rotation angle for data augmentation
translate: 0
gaussian_noise_std: 0.02
additive_brightness_std: 0.7
gamma_range: [0.5, 1.6]

print_freq: 1


# VALIDATION
ema: False
ema_alpha: 0.99
val_frequency: 1



# INFERENCE
sliding_window: False


# DDP
world_size: 1
proc_idx: 0
rank: 0
port: 10000
dist_url: 'tcp://localhost:10000' # make sure the port here is the same as in port
dist_backend: "nccl"
multiprocessing_distributed: true
reproduce_seed: null
