#DATA
data_root: dataset/lits_3d
classes: 3
modality: CT


#MODEL
arch: unetr
in_chan: 1
norm: in
init_model: /research/cbim/vast/yg397/ConvFormer/ConvFormer/initmodel/UNETR_model_best_acc.pth

#TRAIN
epochs: 400
training_size: [96, 96, 96] # training crop size
start_epoch: 0

seed: 0
k_fold: 5

optimizer: adamw
base_lr: 0.0001
betas: [0.9, 0.999]
weight_decay: 0.00005  # weight decay of SGD optimizer
weight: [0.5, 1, 3]
rlt: 1 # relation between CE and Dice loss

scale: [0.3, 0.3, 0.3]  # scale for data augmentation  0.1 0.3 0.3
rotate: [30, 30, 30] # rotation angle for data augmentation 
translate: [0, 0, 0]
gaussian_noise_std: 0.02


iter_per_epoch: 500


#VALIDATION
ema: False
ema_alpha: 0.99
val_frequency: 10



#INFERENCE
sliding_window: True
window_size: [96, 96, 96]
