#DATA
data_root: dataset/bcv_3d
classes: 14
modality: CT


#MODEL
arch: utnetv2
in_chan: 1
base_chan: 32
conv_block: 'BasicBlock'

down_scale: [[1,2,2], [1,2,2], [2,2,2], [2,2,2]]
kernel_size: [[1,3,3], [1,3,3], [3,3,3], [3,3,3], [3,3,3]]
chan_num: [64, 128, 256, 320, 256, 128, 64, 32]
norm: in
act: gelu
map_size: [4,4,4]
conv_num: [2,0,0,0, 0,0,2,2]
trans_num: [0,2,4,6, 4,2,0,0]
num_heads: [1,4,8,10, 8,4,1,1]
expansion: 4
fusion_depth: 2
fusion_dim: 320
fusion_heads: 10
attn_drop: 0
proj_drop: 0
proj_type: 'depthwise'
rel_pos: False
se: True


#TRAIN
epochs: 150
training_size: [32, 128, 128] # training crop size
start_epoch: 0
aux_loss: True
aux_weight: [0.5, 0.5]

seed: 0
k_fold: 5

optimizer: adamw
base_lr: 0.0006
betas: [0.9, 0.999]
#momentum: 0.9   # momentum of SGD optimizer
weight_decay: 0.05  # weight decay of SGD optimizer
weight: [0.5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
rlt: 1 # relation between CE and Dice loss


scale: [0.3, 0.3, 0.3]  # scale for data augmentation  0 0.3 0.3
rotate: [30, 30, 30] # rotation angle for data augmentation 30
translate: [0, 0, 0]
gaussian_noise_std: 0.02


iter_per_epoch: 300




#VALIDATION
ema: True
ema_alpha: 0.99
val_frequency: 10



#INFERENCE
sliding_window: True
window_size: [32, 128, 128]
